
project_id = "ehrerbpblmensiodhgka"
[global.env_variables]
OPENAI_API_KEY = "${env:OPENAI_API_KEY}"
SUPABASE_URL = "${env:SUPABASE_URL}"
SUPABASE_ANON_KEY = "${env:SUPABASE_ANON_KEY}"
WHATSAPP_VERIFY_TOKEN = "ipt-teixeira-webhook-token"
WHATSAPP_TOKEN = "${env:WHATSAPP_TOKEN}"
WHATSAPP_PHONE_NUMBER_ID = "${env:WHATSAPP_PHONE_NUMBER_ID}"
BAILEYS_SESSION_PATH = "${env:BAILEYS_SESSION_PATH}"
