
project_id = "ehrerbpblmensiodhgka"
[global.env_variables]
OPENAI_API_KEY = "OPENAI_API_KEY"
SUPABASE_URL = "SUPABASE_URL"
SUPABASE_ANON_KEY = "SUPABASE_ANON_KEY"
WHATSAPP_VERIFY_TOKEN = "WHATSAPP_VERIFY_TOKEN"
WHATSAPP_TOKEN = "WHATSAPP_TOKEN"
WHATSAPP_PHONE_NUMBER_ID = "WHATSAPP_PHONE_NUMBER_ID"
