
project_id = "ehrerbpblmensiodhgka"
[global.env_variables]
OPENAI_API_KEY = "OPENAI_API_KEY"
SUPABASE_URL = "SUPABASE_URL"
SUPABASE_ANON_KEY = "SUPABASE_ANON_KEY"
N8N_WEBHOOK_URL = "http://localhost:5678/webhook-test/chat-assistant"
